<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bazlama.Modules.Identity\Bazlama.Modules.Identity.csproj" />
    <ProjectReference Include="..\Bazlama.Compiler\Bazlama.Compiler.csproj" />
  </ItemGroup>
</Project>
