using System.Globalization;
using System.Text;
using Bazlama.Engine.Metadata;

namespace Bazlama.Compiler;

/// <summary>
/// C# classes for an app's entities and modals (one per entity or modal, a property per field),
/// compiled together with the app's code so it is typed: <c>siparis.SiparisNo</c>,
/// <c>siparis.Durum == Siparis.DurumValues.Taslak</c>, <c>aralik.Baslangic</c>.
/// </summary>
public static class EntityCodeGenerator
{
    public const string FileName = "_Entities.g.cs";

    /// <summary>"siparis" → namespace SiparisApp (not "Siparis": an entity may have the same name).</summary>
    public static string Namespace(AppDefinition app) => Pascal(app.Key) + "App";

    public static string ClassName(EntityDefinition e) => Pascal(e.Key);
    public static string ClassName(ModalDefinition m) => Pascal(m.Key);
    public static string PropertyName(FieldDefinition f) => Pascal(f.Key);

    public static string Generate(AppDefinition app)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> From the app metadata; do not edit. </auto-generated>");
        // Generated files are outside the nullable context unless they opt in.
        sb.AppendLine("#nullable enable");
        sb.AppendLine("global using System;");
        sb.AppendLine("global using System.Collections.Generic;");
        sb.AppendLine("global using System.Linq;");
        sb.AppendLine("global using System.Threading.Tasks;");
        sb.AppendLine("global using Bazlama.Sdk;");
        sb.AppendLine($"global using {Namespace(app)};");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace(app)};");
        foreach (var e in app.Entities)
        {
            sb.AppendLine();
            sb.AppendLine($"/// <summary>{Escape(e.Name)}{(e.Parent is { } p ? $" (detail of {ClassName(app.Entity(p)!)})" : "")}.</summary>");
            sb.AppendLine($"[Entity(\"{e.Key}\")]");
            sb.AppendLine($"public partial class {ClassName(e)} : Record");
            sb.AppendLine("{");
            Members(sb, app, e.Fields);
            sb.AppendLine("}");
        }
        foreach (var m in app.Modals)
        {
            sb.AppendLine();
            sb.AppendLine($"/// <summary>{Escape(m.Name)} (modal): what the user entered.</summary>");
            sb.AppendLine($"[Modal(\"{m.Key}\")]");
            sb.AppendLine($"public partial class {ClassName(m)} : ModalValues");
            sb.AppendLine("{");
            Members(sb, app, m.Fields);
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    /// <summary>A property per field, and a class of constants per choice field.</summary>
    static void Members(StringBuilder sb, AppDefinition app, IReadOnlyList<FieldDefinition> fields)
    {
        foreach (var f in fields)
        {
            var what = f.Type switch
            {
                FieldType.Reference => $": id of a {ClassName(app.Entity(f.Reference!)!)}",
                FieldType.Company => ": id of a company",
                FieldType.Location => ": id of a location",
                FieldType.Plant => ": id of a plant",
                FieldType.Period => ": id of a period",
                _ => "",
            };
            sb.AppendLine($"    /// <summary>{Escape(f.Label)}{(f.Required ? " (required)" : "")}{what}.</summary>");
            sb.AppendLine($"    [Field(\"{f.Key}\")] public {TypeOf(f)} {PropertyName(f)} {{ get; set; }}");
        }
        foreach (var f in fields.Where(f => f.Type == FieldType.Choice))
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>The values of {PropertyName(f)}.</summary>");
            sb.AppendLine($"    public static class {PropertyName(f)}Values");
            sb.AppendLine("    {");
            var used = new HashSet<string>();
            foreach (var c in f.Choices!)
            {
                var name = Pascal(c.Value);
                if (name.Length == 0 || !char.IsLetter(name[0])) name = "V" + name;
                while (!used.Add(name)) name += "_";
                sb.AppendLine($"        /// <summary>{Escape(c.Label)}</summary>");
                sb.AppendLine($"        public const string {name} = \"{c.Value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\";");
            }
            sb.AppendLine("    }");
        }
    }

    static string TypeOf(FieldDefinition f) => f.Type switch
    {
        FieldType.Text or FieldType.LongText or FieldType.Choice => "string?",
        FieldType.Integer => "long?",
        FieldType.Decimal => "decimal?",
        FieldType.Date => "DateOnly?",
        FieldType.DateTime => "DateTime?",
        FieldType.Boolean => "bool?",
        FieldType.Reference or FieldType.Company or FieldType.Location or FieldType.Plant or FieldType.Period => "Guid?",
        _ => "object?",
    };

    /// <summary>"siparis_no" → "SiparisNo". Keys are a–z, 0–9 and _; anything else is dropped.</summary>
    public static string Pascal(string key)
    {
        var sb = new StringBuilder();
        foreach (var part in key.Split('_', '-', ' ', '.'))
        {
            var clean = new string([.. part.Where(char.IsAsciiLetterOrDigit)]);
            if (clean.Length > 0) sb.Append(char.ToUpper(clean[0], CultureInfo.InvariantCulture)).Append(clean[1..]);
        }
        return sb.ToString();
    }

    static string Escape(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").ReplaceLineEndings(" ");
}
